package model.bo;
// Generated 25 mars 2023 10:31:06 by Hibernate Tools 4.3.1



/**
 * Emprunter generated by hbm2java
 */
public class Emprunter  implements java.io.Serializable {


     private EmprunterId id;
     private Exemplaire exemplaire;
     private Adherent adherent;
     private String datefin;

    public Emprunter() {
    }

	
    public Emprunter(EmprunterId id, Exemplaire exemplaire, Adherent adherent) {
        this.id = id;
        this.exemplaire = exemplaire;
        this.adherent = adherent;
    }
    public Emprunter(EmprunterId id, Exemplaire exemplaire, Adherent adherent, String datefin) {
       this.id = id;
       this.exemplaire = exemplaire;
       this.adherent = adherent;
       this.datefin = datefin;
    }
   
    public EmprunterId getId() {
        return this.id;
    }
    
    public void setId(EmprunterId id) {
        this.id = id;
    }
    public Exemplaire getExemplaire() {
        return this.exemplaire;
    }
    
    public void setExemplaire(Exemplaire exemplaire) {
        this.exemplaire = exemplaire;
    }
    public Adherent getAdherent() {
        return this.adherent;
    }
    
    public void setAdherent(Adherent adherent) {
        this.adherent = adherent;
    }
    public String getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(String datefin) {
        this.datefin = datefin;
    }




}


