package model.bo;
// Generated 25 mars 2023 10:31:06 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EmprunterId generated by hbm2java
 */
public class EmprunterId  implements java.io.Serializable {


     private BigDecimal noexp;
     private String cin;
     private String datedebut;

    public EmprunterId() {
    }

    public EmprunterId(BigDecimal noexp, String cin, String datedebut) {
       this.noexp = noexp;
       this.cin = cin;
       this.datedebut = datedebut;
    }

   
    public BigDecimal getNoexp() {
        return this.noexp;
    }
    
    public void setNoexp(BigDecimal noexp) {
        this.noexp = noexp;
    }
    public String getCin() {
        return this.cin;
    }
    
    public void setCin(String cin) {
        this.cin = cin;
    }
    public String getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(String datedebut) {
        this.datedebut = datedebut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmprunterId) ) return false;
		 EmprunterId castOther = ( EmprunterId ) other; 
         
		 return ( (this.getNoexp()==castOther.getNoexp()) || ( this.getNoexp()!=null && castOther.getNoexp()!=null && this.getNoexp().equals(castOther.getNoexp()) ) )
 && ( (this.getCin()==castOther.getCin()) || ( this.getCin()!=null && castOther.getCin()!=null && this.getCin().equals(castOther.getCin()) ) )
 && ( (this.getDatedebut()==castOther.getDatedebut()) || ( this.getDatedebut()!=null && castOther.getDatedebut()!=null && this.getDatedebut().equals(castOther.getDatedebut()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoexp() == null ? 0 : this.getNoexp().hashCode() );
         result = 37 * result + ( getCin() == null ? 0 : this.getCin().hashCode() );
         result = 37 * result + ( getDatedebut() == null ? 0 : this.getDatedebut().hashCode() );
         return result;
   }   


}


