package model.bo;
// Generated 25 mars 2023 10:31:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Livres generated by hbm2java
 */
public class Livres  implements java.io.Serializable {
    
     private String isbn;
     private String titre;
     private String category;
     private Set exemplaires = new HashSet(0);

    public Livres() {
    }

	
    public Livres(String isbn) {
        this.isbn = isbn;
    }
    public Livres(String isbn, String titre, String category, Set exemplaires) {
       this.isbn = isbn;
       this.titre = titre;
       this.category = category;
       this.exemplaires = exemplaires;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Set getExemplaires() {
        return this.exemplaires;
    }
    
    public void setExemplaires(Set exemplaires) {
        this.exemplaires = exemplaires;
    }
}


