package model.bo;


import java.util.HashSet;
import java.util.Set;

/**
* Adherent generated by hbm2java
*/
public class Adherent  implements java.io.Serializable {


  private String cin;
  private String nom;
  private String prenom;
  private String mdp;
  private String tele;

 public Adherent() {
 }

	
 public Adherent(String cin) {
     this.cin = cin;
 }
 public Adherent(String cin, String nom, String prenom, String mdp, String tele) {
	 
    this.cin = cin;
    this.nom = nom;
    this.prenom = prenom;
    this.mdp = mdp;
    this.tele = tele;
    
 }

 public String getCin() {
     return this.cin;
 }
 
 public void setCin(String cin) {
     this.cin = cin;
 }
 public String getNom() {
     return this.nom;
 }
 
 public void setNom(String nom) {
     this.nom = nom;
 }
 public String getPrenom() {
     return this.prenom;
 }
 
 public void setPrenom(String prenom) {
     this.prenom = prenom;
 }
 public String getMdp() {
     return this.mdp;
 }
 
 public void setMdp(String mdp) {
     this.mdp = mdp;
 }
 public String getTele() {
     return this.tele;
 }
 
 public void setTele(String tele) {
     this.tele = tele;
 }


}


